"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

#VARIABLES DE ENTORNO 
from dotenv import load_dotenv
import os
load_dotenv()

REDIS_URL= os.getenv('REDIS_URL')
SECRET_KEY = os.getenv('SECRET_KEY')
DATABASE_URL = os.getenv('DATABASE_URL')
ORIGIN= os.getenv('ORIGIN')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get("HOST", "localhost").split(",")
CORS_ALLOWED_ORIGINS= [
   ORIGIN
]

CORS_ALLOW_ALL_ORIGINS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'authentication',
    'pacientes',
    'ml',
    'analytics',
    'reportes'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
import dj_database_url 

DATABASES = {
    'default': dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=0,
        ssl_require=True 
    )
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0"),
        "OPTIONS": {

        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

CLINICAL_TEXT_VALUE_MAPPINGS = {
    'presion_sistolica': {'baja': 90.0, 'normal': 120.0, 'alta': 150.0},
    'presion_diastolica': {'baja': 60.0, 'normal': 80.0, 'alta': 95.0},
    'frecuencia_cardiaca': {'baja': 60.0, 'normal': 80.0, 'alta': 110.0},
    'saturacion_oxigeno': {'baja': 90.0, 'normal': 98.0, 'alta': 100.0},
    'glucosa': {'baja': 70.0, 'normal': 100.0, 'alta': 200.0},
    'temperatura': {'baja': 35.5, 'normal': 36.6, 'alta': 38.5},
    'peso': {'baja': 50.0, 'normal': 70.0, 'alta': 100.0},
    'altura': {'baja': 1.50, 'normal': 1.70, 'alta': 1.90},
    'imc': {'baja': 18.5, 'normal': 24.9, 'alta': 30.0},
    'colesterol': {'baja': 150.0, 'normal': 200.0, 'alta': 240.0},
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# LOGGER PARA EL SEGUIMIENTO DEL PROCESO ETL , ML
import os

LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    # 1. FORMATTERS
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name} : {message}',
            'style': '{',
        },
    },
    
    # 2. HANDLERS:
    'handlers': {
        'etl_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'etl.log'),  # logs/etl.log
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'ml_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'ml.log'),   # logs/ml.log
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'an_file':{
        'level': 'INFO',
        'class': 'logging.FileHandler',
        'filename': os.path.join(LOGS_DIR, 'an.log'),
        'formatter': 'verbose',
        'encoding': 'utf-8',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },

    # 3. LOGGERS
    'loggers': {
        'etl_logger': {
            'handlers': ['etl_file', 'console'], 
            'level': 'INFO',
            'propagate': False, # Evita duplicación de logs en la consola base de Django
        },
        'ml_logger': {
            'handlers': ['ml_file', 'console'], 
            'level': 'INFO',
            'propagate': False,
        },

        'an_logger': {
            'handlers': ['an_file','console'],
            'level': 'INFO',
        }
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}
