# Generated by Django 6.0.5 on 2026-05-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.IntegerField(unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3, max_length=5)),
                ('imc', models.DecimalField(db_column='IMC', decimal_places=2, max_digits=5, max_length=5)),
                ('presion_sistolica', models.IntegerField()),
                ('presion_diastolica', models.IntegerField()),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('saturacion_oxigeno', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('glucosa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('colesterol', models.DecimalField(decimal_places=2, max_digits=6)),
                ('antecedentes_familiares', models.BooleanField(default=False)),
                ('fumador', models.BooleanField(default=False)),
                ('consumo_alcohol', models.BooleanField(default=False)),
                ('actividad_fisica', models.CharField(max_length=50)),
                ('diagnostico_preliminar', models.CharField(max_length=150)),
                ('riesgo_enfermedad', models.CharField(max_length=50)),
                ('fecha_consulta', models.DateField()),
            ],
        ),
    ]
