# Generated by Django 6.0.5 on 2026-05-25 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('tiempo_ejecucion', models.FloatField(default=0.0, help_text='Tiempo en segundos')),
                ('estado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido')], default='EXITOSO', max_length=10)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial ETL',
                'verbose_name_plural': 'Historiales ETL',
                'ordering': ['-loaded_at'],
            },
        ),
    ]
