# Generated by Django 6.0.5 on 2026-06-06 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_archivoetl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='id_paciente',
        ),
    ]
