# Generated by Django 6.0.5 on 2026-05-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricasModelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(default='RandomForestClassifier', max_length=100)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(verbose_name='Accuracy (Exactitud)')),
                ('precision', models.FloatField(verbose_name='Precision (Precisión)')),
                ('recall', models.FloatField(verbose_name='Recall (Sensibilidad)')),
                ('f1_score', models.FloatField(verbose_name='F1-Score')),
                ('matriz_confusion', models.TextField(help_text='Matriz que cruza valores reales vs predicciones')),
                ('ruta_archivo_joblib', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Métrica de Modelo',
                'verbose_name_plural': 'Métricas de Modelos',
                'ordering': ['-trained_at'],
            },
        ),
    ]
