# Generated by Django 6.0.5 on 2026-05-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricasmodelos',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
